name: Windows-CSPBot-Server-Helper


on: [push]


jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019 
    # 参考文档 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-latest

    env:
      targetName: CSPBot-Server-Helper
    # 步骤
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          MSBuild.exe ./CSPBot-Server-Helper.sln -property:Configuration=Release
        shell: bash

      - name: MkDirs
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir D:/out/
    
      - name: Copy Out Files
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cp x64/Release/*.exe D:/out/
          cp runner.bat D:/out/
          cp *.js D:/out/
        shell: bash

      - name: Upload plugins
        uses: actions/upload-artifact@v1.0.0
        with:
          name: CSPBot-Server-Helper
          path: D:/out/BuildConfig

      - name: Compress to zip
        run: |
          7z a D:/out/zip/CSPBot-Server-Helper.zip D:/out/
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: CSPBot-Server-Helper ${{env.RELEASE_TAG}}
          body_path: ./CHANGELOG.md
          files: |
            D:/out/zip/CSPBot-${{ steps.vars.outputs.sha_short }}.zip
        env:
            GITHUB_REPOSITORY: CSPBot-Devloper/CSPBot-Server-Helper


  Clean:
    runs-on: ubuntu-latest
    if: ${{ always() }} # 防止前面三者跑着跑着报错，这一步骤不执行导致libs删不掉的现象发生
    needs: [build]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: libs
